In [16]:
## Este projeto contém exercícios práticos de análise de dados utilizando Python, com foco em manipulação de dados com Pandas. 
## acompanhando aulas da Data Science Academy (DSA)

In [17]:
import numpy as np
import pandas as pd

In [18]:
#01 A parti do DataFrame de funcionário abaixo, selecione  e exiba os funcionários do departamento de "vendas" que tem 
# um salário superior R$ 4500

dados = {"nome": ["Ana", "Bruno", "Carla", "Matias", "Eliana", "Fabiano"],
        "Departamento": ["RH", "Vendas", "TI", "Vendas", "RH", "Vendas"],
        "Salário": [4000, 5000, 6200, 4400, 4300,5500]}

df_funcionários = pd.DataFrame(dados)

df_funcionários

condicao_depto = df_funcionários["Departamento"] == "Vendas"

condicao_salairo = df_funcionários["Salário"] > 4500

funcionarios_filtrados = df_funcionários[condicao_depto & condicao_salairo]

funcionarios_filtrados

      nome Departamento  Salário
1    Bruno       Vendas     5000
5  Fabiano       Vendas     5500

In [19]:
#02 Com o DataFrame de vendas abaixo, calcule o total de vendas(Valor) para cada categoria de produto.

data_vendas = { "Categoria": ["Eletronicos",  "Vestuário", "Eletronicos", "Casa", "Vestuário"],
                "Produto": ["TV", "Camiseta", "Notebook", "Sofá", "Calça",],
                "Valor": [2500,80, 4500, 3000, 1000]}

data_vendas1 = pd.DataFrame(data_vendas)

data_vendas1

vendas_por_categoria = data_vendas1.groupby("Categoria")["Valor"].sum()

print(vendas_por_categoria)

Categoria
Casa           3000
Eletronicos    7000
Vestuário      1080
Name: Valor, dtype: int64

In [20]:
#03 A parti do DataFrame de produtos abaixo, crie uma nova coluna chamada preco_com_Desconto que contenha o 
#valor da coluna Preco com 10% desconto

dadosProdutos = {"Produto": ["Monitor", "Teclado", "Mouse", "Webcam"],
                "Preco": [800, 120,70,250]}

df_produtos = pd.DataFrame(dadosProdutos)

df_produtos

df_produtos["Preco_com_Desconto"] = df_produtos["Preco"]* 0.90

df_produtos

   Produto  Preco  Preco_com_Desconto
0  Monitor    800               720.0
1  Teclado    120               108.0
2    Mouse     70                63.0
3   Webcam    250               225.0

In [21]:
#04 No DataFrame de alunos abaixo, subustitua as notas ausentes(NAN) pela média da turma (média da coluna "Nota")

dados_alunos = {"Aluno" : ["Aline", "Bernardo", "Clara", "Marcelo"],
                "Nota" : [8.5, 7.0, np.nan, 9.0]}

df_alunos = pd.DataFrame(dados_alunos)

df_alunos

media_notas = df_alunos["Nota"].mean()

df_alunos[ "Nota"] = df_alunos["Nota"].fillna(media_notas)

df_alunos

      Aluno      Nota
0     Aline  8.500000
1  Bernardo  7.000000
2     Clara  8.166667
3   Marcelo  9.000000

In [22]:
8.5 + 7.0 + 9.0

24.5

In [23]:
24.5 /3

8.166666666666666

In [24]:
#05 Ordene o DataFrame de pontuações abaixo, do maior para o menor com base na coluna "pontos e exiba"
# o resultado. 

dados_pontuacao = {"Dados": ["J1", "J2", "J3", "J4", "J5"],
                    "Pontos": [88,95,74,102,95]}

dados_pontuacao = pd.DataFrame(dados_pontuacao)

dados_pontuacao 

df_ordenado = dados_pontuacao.sort_values(by = "Pontos", ascending = False)

df_ordenado

  Dados  Pontos
3    J4     102
4    J5      95
1    J2      95
0    J1      88
2    J3      74

In [25]:
#06 Combine os DataFrame df_pedidos com base na coluna em comum ID_Cliente

df_cliente = pd.DataFrame({"ID_Cliente": [1,2,3],
                            "Nome": ["Carlos", "Mariana", "Lucas"]})

df_pedidos = pd.DataFrame({"ID_Pedido": [101,102,103],
                           "ID_Cliente": [2,1,2],
                            "Produto": ["Livro","Caneta", "Caderno"]})

df_combinado = pd.merge(df_cliente,df_pedidos, on = "ID_Cliente")

df_combinado

   ID_Cliente     Nome  ID_Pedido  Produto
0           1   Carlos        102   Caneta
1           2  Mariana        101    Livro
2           2  Mariana        103  Caderno

In [26]:
#07 No DataFrame abaixo, extraia o ano da coluna Data e Crie uma nova coluna chamada Ano. 

dados_eventos = {"Evento": ["Conferência A", "Workshop B", "Feira C"],
                "Data": ["2025-10-25", "2026-03-12", "2026-09-01"]}

df_eventos = pd.DataFrame(dados_eventos)

df_eventos

df_eventos.info()

df_eventos["Ano"] = df_eventos["Data"].str.slice(0,4)

df_eventos

df_eventos["Ano"] = pd.to_datetime(df_eventos["Data"]).dt.year

df_eventos

df_eventos["Ano"] = pd.to_datetime(df_eventos["Data"]).dt.year

df_eventos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Evento  3 non-null      object
 1   Data    3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

          Evento        Data   Ano
0  Conferência A  2025-10-25  2025
1     Workshop B  2026-03-12  2026
2        Feira C  2026-09-01  2026

In [27]:
#08 Crie uma nova coluna Status no DataFrame de notas.  Se a nota for maior ou igual 7, O status
#deve ser "APROVADO", caso contrário, "REPROVADO" e use o metodo apply

dados_notas = {"Aluno": ["Maria", "Jeremias", "Paulo", "Roberto"],
              "Nota": [9.5,6.0,5.5,8.0]}

df_notas = pd.DataFrame(dados_notas)

df_notas

df_notas["Status"] = df_notas["Nota"].apply(lambda nota: "Aprovado" if nota >= 7 else "Reprovado")

df_notas

      Aluno  Nota     Status
0     Maria   9.5   Aprovado
1  Jeremias   6.0  Reprovado
2     Paulo   5.5  Reprovado
3   Roberto   8.0   Aprovado

In [28]:
#09 Crie uma tabela dinâmica que mostre a soma das vendas por Religião e Vendedor. 

dados_regional = {"Regiao": ["Norte", "Sul", "Norte", "Sul", "Norte", "Sul"],
                 "Vendedor":["Ana", "Bruno", "Gabriela", "Carlos", "Bruno", "Paulo"],
                 "Vendas": [1000, 1500, 1200, 1800, 800, 1300]}


df_regional = pd.DataFrame(dados_regional)

df_regional

tabela_dinamica = df_regional.pivot_table(index = "Regiao",
                                          columns = "Vendedor", 
                                          values = "Vendas",
                                          aggfunc = "sum",
                                          fill_value = 0)

tabela_dinamica

Vendedor   Ana  Bruno  Carlos  Gabriela  Paulo
Regiao
Norte     1000    800       0      1200      0
Sul          0   1500    1800         0   1300

In [29]:
#10 A partir do DataFrame de visitas de um site, selecione e exiba apenas os registros do mês
#Agosto de 2016.

datas = pd.to_datetime(pd.date_range(start = "2026-07-25", periods = 13, freq = "D"))
dados_visitas = {"visitas": [158,165,178,199,285,225,230,215,240,255,260,258,270]}
df_visitas = pd.DataFrame(data = dados_visitas, index = datas)
df_visitas.index.name = "Data"

df_visitas

            visitas
Data
2026-07-25      158
2026-07-26      165
2026-07-27      178
2026-07-28      199
2026-07-29      285
2026-07-30      225
2026-07-31      230
2026-08-01      215
2026-08-02      240
2026-08-03      255
2026-08-04      260
2026-08-05      258
2026-08-06      270

In [30]:
visitas_agosto = df_visitas.loc["2026-07"]

visitas_agosto

            visitas
Data
2026-07-25      158
2026-07-26      165
2026-07-27      178
2026-07-28      199
2026-07-29      285
2026-07-30      225
2026-07-31      230